## Importing Libraries, Data and Warnings

In [5]:
#importing libraries
#in the terminal write it as pip install (library to install)
import pandas as pd #write this so code recognises pd

#import warnings
import warnings
warnings.simplefilter("ignore", category=FutureWarning)
warnings.simplefilter("ignore", category=DeprecationWarning)


#import data
test=pd.read_csv("Rossman_test.csv")
store=pd.read_csv("Rossman_store.csv")
train=pd.read_csv("Rossman_train.csv") #there is a mix type in column 7

/tmp/ipykernel_9312/725132455.py:14: DtypeWarning: Columns (0: StateHoliday) have mixed types. Specify dtype option on import or set low_memory=False.
  train=pd.read_csv("Rossman_train.csv") #there is a mix type in column 7

## Store Data

In [6]:
store.shape

(1115, 10)

In [7]:
store.head()

,Store,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1,2,a,a,570.0,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
2,3,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
3,4,c,c,620.0,9.0,2009.0,0,NaN,NaN,NaN
4,5,a,a,29910.0,4.0,2015.0,0,NaN,NaN,NaN

In [8]:
store.describe()

,Store,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear
count,1115.00000,1112.000000,761.000000,761.000000,1115.000000,571.000000,571.000000
mean,558.00000,5404.901079,7.224704,2008.668857,0.512108,23.595447,2011.763573
std,322.01708,7663.174720,3.212348,6.195983,0.500078,14.141984,1.674935
min,1.00000,20.000000,1.000000,1900.000000,0.000000,1.000000,2009.000000
25%,279.50000,717.500000,4.000000,2006.000000,0.000000,13.000000,2011.000000
50%,558.00000,2325.000000,8.000000,2010.000000,1.000000,22.000000,2012.000000
75%,836.50000,6882.500000,10.000000,2013.000000,1.000000,37.000000,2013.000000
max,1115.00000,75860.000000,12.000000,2015.000000,1.000000,50.000000,2015.000000

In [ ]:
#fill in missing values

#filled missing values with mean
store["CompetitionDistance"]=store["CompetitionDistance"].fillna(store["CompetitionDistance"].mean())

#fill in any missing years and months with 0
store["CompetitionOpenSinceMonth"]=store["CompetitionOpenSinceMonth"].fillna(0).astype(int)
store["CompetitionOpenSinceYear"]=store["CompetitionOpenSinceYear"].fillna(0).astype(int)

#the store does not have values for promo 2 and promo interval so fill in missing values with 0
store["Promo2SinceWeek"]=store["Promo2SinceWeek"].fillna(0).astype(int)
store["Promo2SinceYear"]=store["Promo2SinceYear"].fillna(0).astype(int)
store["PromoInterval"]=store["PromoInterval"].fillna("None")

In [ ]:
store.to_csv("store_cleaned.csv", index=False)

## Test Data

In [9]:
test.shape

(41088, 8)

In [10]:
test.head

<bound method NDFrame.head of           Id  Store  DayOfWeek        Date  Open  Promo StateHoliday  \
0          1      1          4  2015-09-17   1.0      1            0
1          2      3          4  2015-09-17   1.0      1            0
2          3      7          4  2015-09-17   1.0      1            0
3          4      8          4  2015-09-17   1.0      1            0
4          5      9          4  2015-09-17   1.0      1            0
...      ...    ...        ...         ...   ...    ...          ...
41083  41084   1111          6  2015-08-01   1.0      0            0
41084  41085   1112          6  2015-08-01   1.0      0            0
41085  41086   1113          6  2015-08-01   1.0      0            0
41086  41087   1114          6  2015-08-01   1.0      0            0
41087  41088   1115          6  2015-08-01   1.0      0            0

       SchoolHoliday
0                  0
1                  0
2                  0
3                  0
4                  0
...              ...
41083              0
41084              0
41085              0
41086              0
41087              1

[41088 rows x 8 columns]>

In [11]:
test.describe()

,Id,Store,DayOfWeek,Open,Promo,SchoolHoliday
count,41088.000000,41088.000000,41088.000000,41077.000000,41088.000000,41088.000000
mean,20544.500000,555.899533,3.979167,0.854322,0.395833,0.443487
std,11861.228267,320.274496,2.015481,0.352787,0.489035,0.496802
min,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25%,10272.750000,279.750000,2.000000,1.000000,0.000000,0.000000
50%,20544.500000,553.500000,4.000000,1.000000,0.000000,0.000000
75%,30816.250000,832.250000,6.000000,1.000000,1.000000,1.000000
max,41088.000000,1115.000000,7.000000,1.000000,1.000000,1.000000

In [12]:
#add the date for each month
test["Date"]=pd.to_datetime(test["Date"])

#Open has some missing values so replace with 1 for open as most days that are not filled are weekdays
test["Open"]=test["Open"].fillna(1).astype(int)

In [13]:
test.to_csv("test_cleaned.csv", index=False)

## Training Data

In [14]:
train.shape

(1017209, 9)

In [15]:
train.head

<bound method NDFrame.head of          Store  DayOfWeek        Date  Sales  Customers  Open  Promo  \
0            1          5  2015-07-31   5263        555     1      1
1            2          5  2015-07-31   6064        625     1      1
2            3          5  2015-07-31   8314        821     1      1
3            4          5  2015-07-31  13995       1498     1      1
4            5          5  2015-07-31   4822        559     1      1
...        ...        ...         ...    ...        ...   ...    ...
1017204   1111          2  2013-01-01      0          0     0      0
1017205   1112          2  2013-01-01      0          0     0      0
1017206   1113          2  2013-01-01      0          0     0      0
1017207   1114          2  2013-01-01      0          0     0      0
1017208   1115          2  2013-01-01      0          0     0      0

        StateHoliday  SchoolHoliday
0                  0              1
1                  0              1
2                  0              1
3                  0              1
4                  0              1
...              ...            ...
1017204            a              1
1017205            a              1
1017206            a              1
1017207            a              1
1017208            a              1

[1017209 rows x 9 columns]>

In [16]:
train.describe()

,Store,DayOfWeek,Sales,Customers,Open,Promo,SchoolHoliday
count,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06
mean,5.584297e+02,3.998341e+00,5.773819e+03,6.331459e+02,8.301067e-01,3.815145e-01,1.786467e-01
std,3.219087e+02,1.997391e+00,3.849926e+03,4.644117e+02,3.755392e-01,4.857586e-01,3.830564e-01
min,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,2.800000e+02,2.000000e+00,3.727000e+03,4.050000e+02,1.000000e+00,0.000000e+00,0.000000e+00
50%,5.580000e+02,4.000000e+00,5.744000e+03,6.090000e+02,1.000000e+00,0.000000e+00,0.000000e+00
75%,8.380000e+02,6.000000e+00,7.856000e+03,8.370000e+02,1.000000e+00,1.000000e+00,0.000000e+00
max,1.115000e+03,7.000000e+00,4.155100e+04,7.388000e+03,1.000000e+00,1.000000e+00,1.000000e+00

In [17]:
#Add dates
train["Date"]=pd.to_datetime(train["Date"])

In [18]:
train.to_csv("train_cleaned.csv", index=False)

In [19]:
#check with group:
#check whether to change stateholiday, storetype and assortment as categories
#check whether to merge the train and test files from store now or later