In [3]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

ModuleNotFoundError: No module named 'numpy'

In [ ]:
sales= pd.read_csv("train_cleaned.csv")

In [ ]:
sales.head()

In [5]:
sales.dtypes

Store             int64
DayOfWeek         int64
Date             object
Sales             int64
Customers         int64
Open              int64
Promo             int64
StateHoliday     object
SchoolHoliday     int64
dtype: object

In [ ]:
sales.describe()

In [8]:
top_50 = sales.sort_values('Sales', ascending=False).head(len(sales) // 2)
top_50.head()

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday
44393,909,1,2015-06-22,41551,1721,1,0,0,0
132946,262,5,2015-04-03,38722,5132,1,1,b,0
101726,262,5,2015-05-01,38484,5458,1,1,a,0
87231,262,4,2015-05-14,38367,5192,1,0,a,1
424086,57,1,2014-06-16,38037,1970,1,1,0,0

In [ ]:
top_50.shape

In [ ]:
top_50['StateHoliday'].unique()

In [ ]:
sns.pairplot(top_50)

In [1]:
merged=pd.read_csv("merged.csv")

NameError: name 'pd' is not defined

In [3]:
merged.head()

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,5,31/07/2015,5263,555,1,1,0,1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1,2,5,31/07/2015,6064,625,1,1,0,1,a,a,570.0,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
2,3,5,31/07/2015,8314,821,1,1,0,1,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
3,4,5,31/07/2015,13995,1498,1,1,0,1,c,c,620.0,9.0,2009.0,0,NaN,NaN,NaN
4,5,5,31/07/2015,4822,559,1,1,0,1,a,a,29910.0,4.0,2015.0,0,NaN,NaN,NaN

In [4]:
merged.shape

(1017209, 18)

In [3]:
merged_50 = merged.sort_values('Sales', ascending=False).head(len(merged) // 2)
merged_50.head()

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
44393,909,1,22/06/2015,41551,1721,1,0,0,0,a,c,1680.0,NaN,NaN,1,45.0,2009.0,"Feb,May,Aug,Nov"
132946,262,5,3/04/2015,38722,5132,1,1,b,0,b,a,1180.0,5.0,2013.0,0,NaN,NaN,NaN
101726,262,5,1/05/2015,38484,5458,1,1,a,0,b,a,1180.0,5.0,2013.0,0,NaN,NaN,NaN
87231,262,4,14/05/2015,38367,5192,1,0,a,1,b,a,1180.0,5.0,2013.0,0,NaN,NaN,NaN
424086,57,1,16/06/2014,38037,1970,1,1,0,0,d,c,420.0,6.0,2014.0,0,NaN,NaN,NaN

In [7]:
merged_50.shape

(508604, 18)

In [ ]:
plt.bar(merged_50['Assortment'],merged_50['Sales'])
plt.xlabel("Assortment")
plt.ylabel("Sales")
plt.show()

In [ ]:
plt.bar(merged_50['StateHoliday'],merged_50['Sales'])
plt.xlabel("State Holiday")
plt.ylabel("Sales")
plt.show()

In [ ]:
X = sales[['StateHoliday', 'Assortment', 'CompetitionDistance']]
y = sales['Sales']
X = pd.get_dummies(
    X,
    columns=['StateHoliday', 'Assortment'],
    drop_first=True
)

In [ ]:
X.head()

In [ ]:
X.dtypes

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
model = LinearRegression()

model.fit(X_train, y_train)

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
from sklearn.metrics import r2_score, mean_squared_error

r2 = r2_score(y_test, y_pred)
rmse = mean_squared_error(y_test, y_pred) ** 0.5

print("R²:", r2)
print("RMSE:", rmse)